"""
Tests for src/db.py

Uses the real analytics.db (generated by data/seed.py).
Run:  pytest tests/test_db.py -v
"""

import sqlite3
from pathlib import Path

import pandas as pd
import pytest

# Ensure project root is on the path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.db import execute_query, get_schema_description, SCHEMA_DESCRIPTION


# ── execute_query: happy path ─────────────────────────────────────────────────

class TestExecuteQueryReturnsData:
    def test_returns_dataframe(self):
        df = execute_query("SELECT 1 AS n")
        assert isinstance(df, pd.DataFrame)

    def test_returns_correct_value(self):
        df = execute_query("SELECT 42 AS answer")
        assert df["answer"].iloc[0] == 42

    def test_customers_table_exists(self):
        df = execute_query("SELECT COUNT(*) AS n FROM customers")
        assert df["n"].iloc[0] == 1000

    def test_products_table_exists(self):
        df = execute_query("SELECT COUNT(*) AS n FROM products")
        assert df["n"].iloc[0] == 80

    def test_orders_table_exists(self):
        df = execute_query("SELECT COUNT(*) AS n FROM orders")
        assert df["n"].iloc[0] == 5000

    def test_order_items_table_exists(self):
        df = execute_query("SELECT COUNT(*) AS n FROM order_items")
        assert df["n"].iloc[0] == 15033

    def test_column_names_preserved(self):
        df = execute_query("SELECT customer_id, name, country FROM customers LIMIT 1")
        assert list(df.columns) == ["customer_id", "name", "country"]

    def test_empty_result_returns_empty_dataframe(self):
        df = execute_query(
            "SELECT * FROM customers WHERE customer_id = -999"
        )
        assert isinstance(df, pd.DataFrame)
        assert len(df) == 0

    def test_limit_respected(self):
        df = execute_query("SELECT * FROM customers LIMIT 10")
        assert len(df) == 10


class TestExecuteQueryJoins:
    def test_revenue_query(self):
        df = execute_query("""
            SELECT c.name,
                   ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
            FROM customers c
            JOIN orders o     ON c.customer_id = o.customer_id
            JOIN order_items oi ON o.order_id  = oi.order_id
            WHERE o.status = 'Completed'
            GROUP BY c.customer_id
            ORDER BY revenue DESC
            LIMIT 5
        """)
        assert len(df) == 5
        assert "revenue" in df.columns
        # Revenue should be positive
        assert (df["revenue"] > 0).all()
        # Should be sorted descending
        assert df["revenue"].iloc[0] >= df["revenue"].iloc[-1]

    def test_monthly_grouping(self):
        df = execute_query("""
            SELECT strftime('%Y-%m', order_date) AS month, COUNT(*) AS orders
            FROM orders
            GROUP BY month
            ORDER BY month
        """)
        assert "month" in df.columns
        assert "orders" in df.columns
        assert len(df) > 0
        # Month format should be YYYY-MM
        assert df["month"].iloc[0].count("-") == 1


# ── execute_query: security guard ────────────────────────────────────────────

class TestExecuteQuerySecurity:
    @pytest.mark.parametrize("bad_sql", [
        "DROP TABLE customers",
        "DELETE FROM orders",
        "INSERT INTO customers VALUES (1,'x','x@x.com','US','2024-01-01','SMB')",
        "UPDATE customers SET name = 'hacked'",
        "CREATE TABLE evil (id INTEGER)",
        "; SELECT * FROM customers",
        "  drop table products",          # case-insensitive + leading whitespace
    ])
    def test_blocks_non_select(self, bad_sql):
        with pytest.raises(ValueError, match="Only SELECT queries are allowed"):
            execute_query(bad_sql)

    def test_allows_select_with_leading_whitespace(self):
        df = execute_query("  \n  SELECT 1 AS n")
        assert df["n"].iloc[0] == 1

    def test_allows_uppercase_select(self):
        df = execute_query("SELECT 1 AS n")
        assert len(df) == 1

    def test_allows_lowercase_select(self):
        df = execute_query("select 1 as n")
        assert len(df) == 1


# ── execute_query: malformed SQL ──────────────────────────────────────────────

class TestExecuteQueryMalformedSQL:
    def test_raises_on_nonexistent_table(self):
        with pytest.raises(Exception):
            execute_query("SELECT * FROM nonexistent_table_xyz")

    def test_raises_on_syntax_error(self):
        with pytest.raises(Exception):
            execute_query("SELECT FROM WHERE")


# ── Schema description ────────────────────────────────────────────────────────

class TestSchemaDescription:
    def test_get_schema_description_returns_string(self):
        schema = get_schema_description()
        assert isinstance(schema, str)
        assert len(schema) > 100

    def test_schema_contains_all_tables(self):
        schema = get_schema_description()
        for table in ["customers", "products", "orders", "order_items"]:
            assert table in schema

    def test_schema_contains_key_columns(self):
        schema = get_schema_description()
        for col in ["customer_id", "order_date", "unit_price", "quantity", "segment"]:
            assert col in schema

    def test_schema_contains_revenue_hint(self):
        assert "Revenue" in SCHEMA_DESCRIPTION

    def test_schema_contains_strftime_hint(self):
        assert "strftime" in SCHEMA_DESCRIPTION

    def test_schema_mentions_completed_filter(self):
        assert "Completed" in SCHEMA_DESCRIPTION

    def test_get_schema_description_matches_constant(self):
        assert get_schema_description() == SCHEMA_DESCRIPTION
